port: 9090
debug: true
openOnStart: false
locale: zh_CN
dotfiles: ignore # dotfiles: [allow|deny|ignore]
path:
  zfinder: /__ZFINDER__
  handler: /__ZFINDER_HANDLER__
handler:
  # basic authorization
  basic-auth:
    ignores:
      # audios
      - \.(wav|bwf|raw|aiff|flac|m4a|pac|tta|wv|ast|aac|mp2|mp3|mp4|amr|s3m|3gp|act|au|dct|dss|gsm|m4p|mmf|mpc|ogg|oga|opus|ra|sln|vox)$
      # code
      - \.(css|js|json|map)$
      # documents
      - \.(htm|html|markdown|md|pdf|xmind)$
      # fonts
      - \.(eot|svg|ttf|woff|woff2)$
      # images
      - \.(ase|art|bmp|blp|cd5|cit|cpt|cr2|cut|dds|dib|djvu|egt|exif|gif|gpl|grf|icns|ico|iff|jng|jpeg|jpg|jfif|jp2|jps|lbm|max|miff|mng|msp|nitf|ota|pbm|pc1|pc2|pc3|pcf|pcx|pdn|pgm|PI1|PI2|PI3|pict|pct|pnm|pns|ppm|psb|psd|pdd|psp|px|pxm|pxr|qfx|raw|rle|sct|sgi|rgb|int|bw|tga|tiff|tif|vtf|xbm|xcf|xpm|3dv|amf|ai|awg|cgm|cdr|cmx|dxf|e2d|egt|eps|fs|gbr|odg|svg|stl|vrml|x3d|sxd|v2d|vnd|wmf|emf|art|xar|png|webp|jxr|hdp|wdp|cur|ecw|iff|lbm|liff|nrrd|pam|pcx|pgf|sgi|rgb|rgba|bw|int|inta|sid|ras|sun|tga)$
      # videos
      - \.(3g2|3gp|aaf|asf|avchd|avi|drc|flv|m2v|m4p|m4v|mkv|mng|mov|mp2|mp4|mpe|mpeg|mpg|mpv|mxf|nsv|ogg|ogv|qt|rm|rmvb|roq|svi|vob|webm|wmv|yuv)$
    users:
      zfinder: awesome
  # file system
  mkdir:
  readdir:
  rename:
  rmdir:
  # automatically add a suffix to current url
  serve-index:
    # priority: 100
    priority: -1
    suffixes:
      - .markdown
      - .md
      - /index.html
      - /index.htm
      - /readme.markdown
      - /readme.md
      - .html
      - .htm
