
port: 9090
debug: true
openOnStart: false
locale: zh_CN
#favicon:
path:
    middlewareRoot: /__ZFINDER_MW__
    zfinderRoot: /__ZFINDER__
middleware:
    zfinder-mw-basic-auth:
    zfinder-mw-fs:
    zfinder-mw-index:
    zfinder-mw-search:
    zfinder-mw-directory:
    #zfinder-mw-audio:
    #zfinder-mw-image:
    #zfinder-mw-json:
    #zfinder-mw-markdown:
    #zfinder-mw-video:
    #zfinder-mw-xmind:
    #zfinder-mw-xml:
    #zfinder-mw-yaml:

